//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muhasebe_otomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBborc
    {
        public string ID { get; set; }
        public string ad_soyad { get; set; }
        public string tel { get; set; }
        public string adres { get; set; }
        public Nullable<int> miktar { get; set; }
    }
}
