//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muhasebe_otomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBgider
    {
        public int ID { get; set; }
        public string giderad { get; set; }
        public Nullable<int> gidertutar { get; set; }
        public Nullable<int> personel { get; set; }
        public Nullable<System.DateTime> gidertarih { get; set; }
        public string gideracıklama { get; set; }
    
        public virtual DBpersonel DBpersonel { get; set; }
    }
}
