//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muhasebe_otomasyon.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class muhasebemEntities : DbContext
    {
        public muhasebemEntities()
            : base("name=muhasebemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBgider> DBgider { get; set; }
        public virtual DbSet<DBkullanici> DBkullanici { get; set; }
        public virtual DbSet<DBmusteri> DBmusteri { get; set; }
        public virtual DbSet<DBpersonel> DBpersonel { get; set; }
        public virtual DbSet<DBurun> DBurun { get; set; }
        public virtual DbSet<DBborc> DBborc { get; set; }
    }
}
